### ISSUE TITLE
Parametric routes: identifying the matched URL path

### ISSUE THREAD

**Issue by robtweed** [bunsvr/router#11]
Within the handler of a parametric route handler, is there a programmatic way to get the parametric URL path that was matched, eg:

    router.get('/token/:token', (req) => {
      // req.url returns the actual instance of the url that was sent
     //   is there a way to get the fact it matched /token/:token,
     //  other than hard-coding in each handler method logic? 
    });
Many thanks for any advice/suggestions

**Comment by robtweed** [comment]
Ignore this - I have a solution

**Comment by aquapi** [comment]
@robtweed read the docs bro
just req.params.token

**Comment by robtweed** [comment]
> @robtweed read the docs bro just req.params.token

I think you misunderstood my question - I know you can access the parameter values via req.params.  What I was wanting was a way to find, via the req object, the parameterised URL that was matched by the specific incoming one.  However, I discovered I didn't need that after all and could identify it another way.  You might want to consider if/how to provide it though for others.
