### ISSUE TITLE
Register a function to be executed before all requests matching path - like a middleware

### ISSUE THREAD

**Issue by henriqueccapozzi** [bunsvr/router#13]
Hello there, 

Is there a way to have a function that acts like a middleware applying custom business logic to all requests matching a certain path pattern

In a very simple example, I tried the following

```js
export default new Router({hostname: "0.0.0.0"})
  .use('GET', "/*", ctx => {
    console.log(`Applying super complex business rules to all requests where path matches /*`);
  })
  .get("/view/*", dir("./public"));
  .post("/upload/*", ctxHandler_upload, { body: "text" }); 
```

And I would like the business logic code to be applied to all requests

**Comment by aquapi** [comment]
@henriqueccapozzi See this
https://stricjs.netlify.app/#/basic/routing/main?id=guarding-routes

**Comment by henriqueccapozzi** [comment]
@aquapi thanks for the guide
I'll test and update here

**Comment by henriqueccapozzi** [comment]
Unfortunately that didn't worked either

The bellow code

```js
import { Router } from '@stricjs/router';
const app = new Router();
app.guard('/',  (ctx) => ctx.headers.get('Authorization') === 'admin' || null);
app.get('/', (ctx) => new Response('Hello World'));
console.log('Started server');

export default app;
```

Got me the following results
![image](https://github.com/bunsvr/router/assets/38324844/c3ab0a45-c6b6-4cf5-90fb-934bc82a4a71)

**Comment by henriqueccapozzi** [comment]
Sorry @aquapi 
that did work 🎉 
Final code was

```js
import { Router } from '@stricjs/router';
const app = new Router();
app.guard('/',  (ctx) => {
  console.log(new Date().toISOString() + ` - Received method ${ctx.method} to path ${new URL(ctx.url).pathname}`);
  return ctx;
});
app.get('/', (ctx) => new Response('Hello World'));
app.get('/foo', (ctx) => new Response('bar'));
app.post('/upload', (ctx) => new Response('upload route'));
console.log('Started server');

export default app;
```

Something to note is that the `.guard` doesn't use a `*` to match routes
