### ISSUE TITLE
Any way to use a callback within a route, without using a Promise wrapper?

### ISSUE THREAD

**Issue by robtweed** [bunsvr/router#16]
The handler code in Stric routes appears to require a Response object to always be returned.

Unless I'm missing something, this means that in order to use an "old school" asynchronous module with a callback, the only solution would seem to be that you must wrap it in a Promise - which adds overhead to its use.

Is there any other approach that would allow me to use a callback directly within a handler?

Thanks

**Comment by aquapi** [comment]
If you want that I'm making a response wrapper for each independent route.
It simply still requires it but you can split your logic of the main one and the one handling the response.
It works like normal wrappers.
Do you want this feature now @robtweed?

Or if you simply want `await`, just make the handler async.

**Comment by aquapi** [comment]
You can see the preview of the feature in the github README

**Comment by robtweed** [comment]
> If you want that I'm making a response wrapper for each independent route. It simply still requires it but you can split your logic of the main one and the one handling the response. It works like normal wrappers. Do you want this feature now @robtweed?
> 
> Or if you simply want `await`, just make the handler async.

I'm not sure I understand.  It doesn't help that I don't know what you mean by "normal wrappers" - I've not seen this concept before in a JS web server.  Could you perhaps provide a simple worked example, using eg setTimeout to show how to define an async route handler with a classic callback so I can properly "get it"?  

Many thanks!

**Comment by aquapi** [comment]
If you want to use Stric in that way (like Node.js style)
You can use a direct ReadableStream and add 'Connection': 'keep-alive'
Direct readable stream has a controller for you to write data
and you can close the connection by `controller.close()` @robtweed

**Comment by aquapi** [comment]
https://bun.sh/docs/api/streams#direct-readablestream
```typescript
app.get('/', () => new Response(
    new ReadableStream({
        type: 'direct',
        pull(c) {
            c.write('Hi ');
            setTimeout(() => {
                c.write('There');
                c.close();
            }, 1000);
        }
    })
));
```

**Comment by aquapi** [comment]
Although this is not recommended but in some cases that is needed

**Comment by robtweed** [comment]
> https://bun.sh/docs/api/streams#direct-readablestream
> 
> ```ts
> app.get('/', () => new Response(
>     new ReadableStream({
>         type: 'direct',
>         pull(c) {
>             c.write('Hi ');
>             setTimeout(() => {
>                 c.write('There');
>                 c.close();
>             }, 1000);
>         }
>     })
> ));
> ```

Interesting!  Many thanks for this example which helps a great deal.

One follow-up question if I may: is it possible, using this approach, to dynamically change the response headers and/or HTTP status code within the callback, eg if an error needs reporting back to the client rather than a successful response?

Many thanks for the great support!

**Comment by robtweed** [comment]
> https://bun.sh/docs/api/streams#direct-readablestream
> 
> ```ts
> app.get('/', () => new Response(
>     new ReadableStream({
>         type: 'direct',
>         pull(c) {
>             c.write('Hi ');
>             setTimeout(() => {
>                 c.write('There');
>                 c.close();
>             }, 1000);
>         }
>     })
> ));
> ```

Interesting!  Many thanks for this example.

Unfortunately I don't think it's what I can use though, since I need to be able to potentially modify the HTTP status code and/or Response Headers from within the callback logic.  For example, the callback logic may determine that a 400 error response should be returned to the client instead of a successful response.

In the example above, the headers have already been written and sent to the client whilst the body is being waiting to be generated in the callback.

I suspect my original Promise wrapper around the callback is the most pragmatic solution, and I know it works OK.
