### ISSUE TITLE
How to set the CORS headers properly

### ISSUE THREAD

**Issue by jeroenrinzema** [bunsvr/router#17]
Hi,

I am attempting to set the CORS headers for a small application I am working on. According to the documentation should I be able to simply wrap the CORS headers using the `wrap` method. The CORS options are not set when I add the wrapper like this.

```js
import { CORS, writeHead } from '@stricjs/utils'; 
import { Router } from '@stricjs/router';

const router = new Router()

const cors = new CORS({
    allowOrigins: '*',
    allowMethods: ['POST', 'GET', 'OPTIONS'],
})

const send = writeHead(cors.headers);

router.post('/v1/calculator/project', async (req) => {})
router.get('/v1/materials', async (req) => {})

router.wrap('/', send);
router.listen()
```

**Comment by aquapi** [comment]
I think I made a mistake in the docs
It should be `writeHead({ headers: cors.headers })`;

**Comment by aquapi** [comment]
What header does it respond? @jeroenrinzema 
Or no header at all?

**Comment by jeroenrinzema** [comment]
Hi @aquapi, no header at all at the moment.

**Comment by jeroenrinzema** [comment]
The CORS headers are returned when I set the headers in a object:

```js
router.wrap('/', writeHead({ headers: cors.headers }));
```

The only problem now is that the response body contains `[object Promise]` instead of the expected response body. The correct response body is returned when I remove the `router.wrap`.

```bash
$ curl 127.0.0.1:3000/v1/materials -v
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /v1/materials HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST,GET,OPTIONS
< content-type: text/plain;charset=utf-8
< Date: Tue, 26 Sep 2023 06:48:35 GMT
< Content-Length: 16
<
* Connection #0 to host 127.0.0.1 left intact
[object Promise]%
```

**Comment by aquapi** [comment]
@jeroenrinzema I think there is an issue with chaining

**Comment by aquapi** [comment]
@jeroenrinzema I will try to reproduce it with 4.2.4

**Comment by jeroenrinzema** [comment]
@aquapi feel free to let me know if you need help with debugging this issue.

**Comment by aquapi** [comment]
@jeroenrinzema 
![image](https://github.com/bunsvr/router/assets/87530663/2fc52201-4d86-4562-8896-6de32c855398)
This works properly in 4.2.5

**Comment by jeroenrinzema** [comment]
Hi, yes it seems this is working in 4.2.5. The issue persists when I try to return a `Response.json()` object. The CORS headers are set:

```bash
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /something HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST,GET,OPTIONS
< content-type: application/octet-stream
< Date: Fri, 29 Sep 2023 11:49:19 GMT
< Content-Length: 17
<
* Connection #0 to host localhost left intact
[object Response]%
```

```js
router.get('/something', async (req) => Response.json({ message: 'hello world' }))
router.wrap('/', writeHead({ headers: cors.headers }));
```

**Comment by aquapi** [comment]
@jeroenrinzema You can do this instead.

```typescript
import { extend } from '@stricjs/utils';

const { headers } = cors;
extend(headers, { 'Content-Type': 'application/json' });

const wrapCORS = writeHead({ headers });

router.get('/something', () => { message: 'hello world' })
router.wrap('/', res => wrapCORS(JSON.stringify(res)));
```

If you want to add additional headers see [createHead](https://stricjs.netlify.app/#/basic/utils/quick-response).

I will do a wrapper for this later on so you can simply set the header with `ctx.head`.

Or another way is to:
```typescript
router.get('/', c => {
    c.head = cors.headers;
    return { message: 'Hello world' };  
}, { wrap: 'sendJSON' });
```

**Comment by aquapi** [comment]
Note that `wrap` is a new feature in 4.2.5
See the docs here: https://stricjs.netlify.app/#/basic/routing/main?id=response-wrappers

**Comment by jeroenrinzema** [comment]
@aquapi thanks this works! I think this is a little but unintuitive. I would expect that the cors wrapper acts like a middleware function appending the cors headers to the response. Is this something you might consider adding/supporting in this project?

**Comment by aquapi** [comment]
@jeroenrinzema read https://stricjs.netlify.app/#/basic/utils/quick-response
and https://stricjs.netlify.app/#/basic/utils/cors
It is really important for you to learn the basic of Stric APIs
