### ISSUE TITLE
Parameters with different name in same location

### ISSUE THREAD

**Issue by jeengbe** [bunsvr/router#18]
```ts
const app = new Router();

app.get('/:a', () => null).post('/:b', () => null);

app.fetch;
```

`=> Cannot create route "/:b" with parameter "b" because a route already exists with a different parameter name ("a") in the same location`

That's a weird limitation, especially if multiple HTTP verbs are used.

**Comment by aquapi** [comment]
Yep you cannot do that because
Stric validates the URL first then the request method
Because checking for paths is often faster than for method (especially when that is not found)
I believe many will have this limitation too if they match URL first @jeengbe .

**Comment by aquapi** [comment]
@jeengbe I uses the @medley/router Trie algorithm.
But I compile the tree Ahead-of-time to create optimal JavaScript code.
See https://github.com/bunsvr/router/tree/main/src/core/router/compiler

You can see the result function body by simply printing out `app.meta.body`
