### ISSUE TITLE
Some paths hit 404 with certain paths configured

### ISSUE THREAD

**Issue by karl-run** [bunsvr/router#2]
I was migrating a express app to @stricjs/router when I found this strange issue.

Here's a minimal repro server:
```typescript
import { Router } from '@stricjs/router';

const router = new Router();

router.get('/dekoratoren/api/sok', async (req: Request) => {
  return new Response('OK sok');
});

router.get('/footer', async (req) => {
  return new Response('OK footer');
});

router.get('/header', async (req) => {
  return new Response('OK header');
});

router.get('/data/:key', async (req) => {
  return new Response('OK data ' + req.params.key);
});

router.get('/', async (req) => {
  return new Response('OK root');
});

router.use(
  404,
  (req) =>
    new Response(`Unable to find: ${req.url}`, {
      status: 404,
    }),
);

export default router;
```

The routes `/`, `/header` and `/footer` work as expected, but `/data/:key` and `/dekoratoren/api/sok` both return 404. However, if you remove either of those two routes, the other one starts working.

**Comment by karl-run** [comment]
Here's a quick script to hit all the endpoints:

```bash
curl http://localhost:3000/
echo
curl http://localhost:3000/header
echo
curl http://localhost:3000/footer
echo
curl http://localhost:3000/data/test-id
echo
curl http://localhost:3000/dekoratoren/api/sok
```

Output with all routes configured:
```
OK root
OK header
OK footer
Unable to find: http://localhost:3000/data/test-id
Unable to find: http://localhost:3000/dekoratoren/api/sok% 
```



Output with `/data/:id` removed:
```
OK root
OK header
OK footer
Unable to find: http://localhost:3000/data/test-id
OK sok%   
```



Output with `/dekoratoren/api/sok` removed:
```
OK root
OK header
OK footer
OK data test-id
Unable to find: http://localhost:3000/dekoratoren/api/sok%
```

**Comment by aquapi** [comment]
Yea some issues with composing
![image](https://github.com/bunsvr/router/assets/87530663/e61ea77a-2543-4c1f-9cbe-5897088ccfbc)
This part should start at 1 not 2

**Comment by aquapi** [comment]
This seems to be an issue with multiple inerts

**Comment by aquapi** [comment]
Oh wait the node tree is incorrectly fixed

**Comment by aquapi** [comment]
I fixed it
The reason this occured is that I forgot to call fixNode 
Thank you for pointing out the issue
Soon enough I will have a patch, 4.0.4
I will notify you and close the issue

**Comment by aquapi** [comment]
@karl-run Now it works normally in 4.0.4

**Comment by aquapi** [comment]
One more thing I recommend when using Stric (and other frameworks as well)
Use sync handlers as much as possible and minimizing memory allocations (creating functions and objects) @karl-run
