### ISSUE TITLE
can't get the store object

### ISSUE THREAD

**Issue by mortezaom** [bunsvr/router#8]
Hey,
I start working around with Stric and try different staffs on it.
one thing that I notice is which the `store` object is undefined or empty while getting from handler.
Also the storage object is not available in Group objects.

Hope to see these items fixed/added to the Stric and I am trying to check  the repo and if possible make some contributions on it.

**Comment by aquapi** [comment]
Did you call store()?

**Comment by aquapi** [comment]
@mortezaom store is normally undefined when the store is not created

To use the store you need to add some key value pair to it first:
```typescript
app.store('count', 1);
```

Sonething like that
You can use different values as well

If you call store() but store is still undefined you can tell me

**Comment by aquapi** [comment]
Group is not meant to have store because store is a global thing
I'm planning to make `ctx.session`, which is like guard but different on every request

**Comment by mortezaom** [comment]
@aquapi this is my code:
![image](https://github.com/bunsvr/router/assets/32927231/518d777e-6200-45e5-9c18-938e09fe6ff7)

and the response is this:
![image](https://github.com/bunsvr/router/assets/32927231/c51822ee-0420-4a56-adfd-0ac8cdfedcd0)

the store object is something else with type of `DebugHTTPServer`, instead of a key-value store

**Comment by aquapi** [comment]
@mortezaom I see the issue
I will publish 4.1.3 tonight (my time rn is 18:47) with the bug fixed and a new `mock` function for testing APIs

**Comment by aquapi** [comment]
![image](https://github.com/bunsvr/router/assets/87530663/cb43245b-e830-48e7-a49b-ccb3a6d748db)
This is my mistake

**Comment by aquapi** [comment]
![image](https://github.com/bunsvr/router/assets/87530663/f73db21e-708a-4d70-ba79-e5b5af5cd088)
@mortezaom You can do this to inspect what actually goes wrong

**Comment by mortezaom** [comment]
By the way I will close this issue and i will check the new release after you push the update.

any plan to add some middleware options for requests or global middleware?

Also if you have any feature in your todos, i can help you with that.

**Comment by aquapi** [comment]
@mortezaom Middleware is slow, I see many does suggest that
I know you guys like it but it is not worth it, believe me

**Comment by aquapi** [comment]
@mortezaom This is what i'm planning to add
![image](https://github.com/bunsvr/router/assets/87530663/9b657db2-67dc-45e3-8d90-d727cd6d4318)

**Comment by mortezaom** [comment]
> @mortezaom Middleware is slow, I see many does suggest that I know you guys like it but it is not worth it, believe me

As you know, a framework must sufficiently meet the basic needs of the programmer, and middleware is one of them for writing APIs.

We can have another handler like Group which has the ability to inject different middleware.
In this way, performance will be a choice for the programmer. If it uses the main Router, the requests will be handled with the best performance, and if developer wants to add middleware, it will pay the price.

**Comment by aquapi** [comment]
@mortezaom 4.1.3 is released
I don't want them to pay the price, especially for new devs
I will write an explaination why you shouldn't use middleware
